#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmypaint
Version  : 1.3.0
Release  : 1
URL      : https://github.com/mypaint/libmypaint/releases/download/v1.3.0/libmypaint-1.3.0.tar.xz
Source0  : https://github.com/mypaint/libmypaint/releases/download/v1.3.0/libmypaint-1.3.0.tar.xz
Summary  : MyPaint's brushstroke rendering library (@LIBMYPAINT_VERSION_FULL@)
Group    : Development/Tools
License  : HPND
Requires: libmypaint-lib
Requires: libmypaint-locales
Requires: libmypaint-data
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libprofiler)

%description
# libmypaint - MyPaint brush engine library
[![Translation Status](https://hosted.weblate.org/widgets/mypaint/libmypaint/svg-badge.svg)](https://hosted.weblate.org/engage/mypaint/?utm_source=widget)
[![Travis Build Status](https://travis-ci.org/mypaint/libmypaint.svg?branch=master)](https://travis-ci.org/mypaint/libmypaint)
[![Appveyor Build Status](https://ci.appveyor.com/api/projects/status/github/mypaint/libmypaint?branch=master&svg=true)](https://ci.appveyor.com/project/jonnor/libmypaint)

%package data
Summary: data components for the libmypaint package.
Group: Data

%description data
data components for the libmypaint package.


%package dev
Summary: dev components for the libmypaint package.
Group: Development
Requires: libmypaint-lib
Requires: libmypaint-data
Provides: libmypaint-devel

%description dev
dev components for the libmypaint package.


%package lib
Summary: lib components for the libmypaint package.
Group: Libraries
Requires: libmypaint-data

%description lib
lib components for the libmypaint package.


%package locales
Summary: locales components for the libmypaint package.
Group: Default

%description locales
locales components for the libmypaint package.


%prep
%setup -q -n libmypaint-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524853658
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1524853658
rm -rf %{buildroot}
%make_install
%find_lang libmypaint

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/MyPaint-1.3.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libmypaint/mypaint-brush-settings-gen.h
/usr/include/libmypaint/mypaint-brush-settings.h
/usr/include/libmypaint/mypaint-brush.h
/usr/include/libmypaint/mypaint-config.h
/usr/include/libmypaint/mypaint-fixed-tiled-surface.h
/usr/include/libmypaint/mypaint-glib-compat.h
/usr/include/libmypaint/mypaint-mapping.h
/usr/include/libmypaint/mypaint-rectangle.h
/usr/include/libmypaint/mypaint-surface.h
/usr/include/libmypaint/mypaint-tiled-surface.h
/usr/lib64/libmypaint.so
/usr/lib64/pkgconfig/libmypaint.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmypaint-1.3.so.0
/usr/lib64/libmypaint-1.3.so.0.0.0

%files locales -f libmypaint.lang
%defattr(-,root,root,-)

